version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Maps port 80 in the container to port 8080 on the host
    volumes:
      - ./build:/usr/local/apache2/htdocs
    restart: always
