version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Expose port 8080 on the host to port 80 on the container
    volumes:
      - ./dist:/usr/local/apache2/htdocs  # Map the dist directory to the Apache htdocs directory
    restart: always
